
server:
  port: 9003

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fuelDb

  kafka:
    producer:
      bootstrap-servers: localhost:9092   
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: reserved
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

order:
 topic:
   name: orderService-topic
   
auto:
  create:
    topics:
      enable: true